name: Gitpod-image-build

# Controls when the action will run.
on:
  push:
    paths:
    - '.gitpod.Dockerfile'
  pull_request:
    branches: [ main ]
    paths:
    - '.gitpod.Dockerfile'

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.1.1
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.3.0
        with:
          # Path to the Dockerfile
          file: '.gitpod.Dockerfile'
          # List of tags
          tags: ${{ github.repository }}
