name: Go

on:
  push:
    paths:
      - "**.go"
      - "sonar-project.properties"
      - "**/go.yml"
  pull_request:
    branches: [main]
    paths:
      - "**.go"
      - "sonar-project.properties"
      - "**/go.yml"

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run golangci-lint
        # You may pin to the exact commit or the version.
        # uses: golangci/golangci-lint-action@544d2efb307b3f205f34886f2787046abe7fb26e
        uses: golangci/golangci-lint-action@v2.4.0
        with:
          # version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest

      - name: Run all tests and find code coverage
        run: go test -v -bench . -benchmem -coverprofile coverage.out ./...
      # - name: SonarCloud Scan
      #   uses: SonarSource/sonarcloud-github-action@v1.5
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      # - name: Convert coverage to lcov
      #   uses: jandelgado/gcov2lcov-action@v1.0.8
      # - name: Coveralls
      #   uses: coverallsapp/github-action@v1.1.2
      #   with:
      #     github-token: ${{ secrets.github_token }}
      #     path-to-lcov: coverage.lcov
  build:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: go build -v .

      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: downloader-${{ matrix.os }}
          path: downloader*
